### ISSUE TITLE
[EliteMobs] Task #62 for EliteMobs v9.1.1 generated an exception

### ISSUE THREAD

**Issue by servicomcr** [MagmaGuy/EliteMobs#166] opened 2024-08-04 18:23 UTC
[19:22:49 WARN]: [EliteMobs] Task #62 for EliteMobs v9.1.1 generated an exception
java.lang.UnsupportedOperationException: remove
        at java.base/java.util.Iterator.remove(Iterator.java:102) ~[?:?]
        at java.base/java.util.AbstractCollection.remove(AbstractCollection.java:285) ~[?:?]
        at EliteMobs (3).jar/com.magmaguy.elitemobs.powers.meta.CustomSummonPower.replaceOldFormat(CustomSummonPower.java:428) ~[EliteMobs (3).jar:?]
        at EliteMobs (3).jar/com.magmaguy.elitemobs.powers.meta.CustomSummonPower.processOldFormats(CustomSummonPower.java:375) ~[EliteMobs (3).jar:?]
        at EliteMobs (3).jar/com.magmaguy.elitemobs.powers.meta.CustomSummonPower.addEntry(CustomSummonPower.java:100) ~[EliteMobs (3).jar:?]
        at EliteMobs (3).jar/com.magmaguy.elitemobs.powers.meta.CustomSummonPower.<init>(CustomSummonPower.java:43) ~[EliteMobs (3).jar:?]
        at EliteMobs (3).jar/com.magmaguy.elitemobs.mobconstructor.custombosses.ElitePowerParser.parsePowers(ElitePowerParser.java:33) ~[EliteMobs (3).jar:?]
        at EliteMobs (3).jar/com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossEntity.setCustomBossesConfigFields(CustomBossEntity.java:167) ~[EliteMobs (3).jar:?]
        at EliteMobs (3).jar/com.magmaguy.elitemobs.mobconstructor.custombosses.CustomBossEntity.<init>(CustomBossEntity.java:121) ~[EliteMobs (3).jar:?]
        at EliteMobs (3).jar/com.magmaguy.elitemobs.mobconstructor.CustomSpawn.lambda$new$0(CustomSpawn.java:71) ~[EliteMobs (3).jar:?]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at EliteMobs (3).jar/com.magmaguy.elitemobs.mobconstructor.CustomSpawn.<init>(CustomSpawn.java:65) ~[EliteMobs (3).jar:?]
        at EliteMobs (3).jar/com.magmaguy.elitemobs.events.TimedEvent.instantiateEvent(TimedEvent.java:116) ~[EliteMobs (3).jar:?]
        at EliteMobs (3).jar/com.magmaguy.elitemobs.events.TimedEvent.pickEvent(TimedEvent.java:99) ~[EliteMobs (3).jar:?]
        at EliteMobs (3).jar/com.magmaguy.elitemobs.events.TimedEvent$1.run(TimedEvent.java:75) ~[EliteMobs (3).jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.jar:1.21-2272-b2d1fea]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.jar:1.21-2272-b2d1fea]

**Comment by MagmaGuy** [comment] 2024-08-04 20:30
Closing here as the problem is being handled in discord.

**Closed by MagmaGuy** 2024-08-04 20:30 UTC
